spring.application.name=wms

# ==================================
# DATABASE
# ==================================
spring.datasource.url=jdbc:postgresql://localhost:5432/wms_db_clean
spring.datasource.username=postgres
spring.datasource.password=error404
spring.datasource.driver-class-name=org.postgresql.Driver

logging.level.org.springframework.security=DEBUG

# ==================================
# JPA
# ==================================
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ==================================
# FLYWAY
# ==================================
spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=true

# ==================================
# SERVER
# ==================================
server.port=8081

# ==================================
# QUOTATIONS
# ==================================
wms.quotation.upload-dir=uploads/quotations

# ==================================
# AI
# ==================================
openai.api-key=${OPENAI_API_KEY:}
openai.model=${OPENAI_MODEL:gpt-4.1-mini}
openai.base-url=https://api.openai.com/v1/responses

jwt.secret=8f4a6c2d9b7e1f3a5c8d0e2f4b6a8c1d9e7f3a5b8c2d6e1f4a7b9c3d5e8f1a2
jwt.expiration=86400000
