"use client";
import {useState} from "react";
import {procurementApi} from "@/lib/api";

const statusClass=(s:string)=>s.includes("CLEAR")||s.includes("MATCH")?"approved":s.includes("EXCEPTION")?"blocked":"pending";
export default function GrIrReconciliation(){
 const [poId,setPoId]=useState("");const [result,setResult]=useState<any>(null);const [loading,setLoading]=useState(false);const [message,setMessage]=useState("");
 const reconcile=async()=>{setLoading(true);setMessage("");try{setResult(await procurementApi.grIr(poId));}catch(e){setMessage(e instanceof Error?e.message:"Unable to reconcile purchase order.");}finally{setLoading(false);}};
 const close=async()=>{setLoading(true);try{setResult(await procurementApi.closeGrIr(poId));setMessage("GR/IR item closed successfully.");}catch(e){setMessage(e instanceof Error?e.message:"Unable to close GR/IR item.");}finally{setLoading(false);}};
 return <div className="content"><div className="page-head"><div><div className="eyebrow">PROCUREMENT / FINANCIAL CONTROL</div><h1>GR/IR Reconciliation</h1><p>Compare purchase order, goods receipt and vendor invoice values, then close a reconciled GR/IR balance.</p></div></div>{message&&<div className="alert">{message}</div>}
 <section className="card form-card"><div className="section-title">Reconciliation Lookup</div><div className="form-grid"><div className="form-field"><label>Purchase Order ID *</label><input className="form-input" value={poId} onChange={e=>setPoId(e.target.value)} placeholder="UUID of purchase order" /></div><div className="form-field" style={{justifyContent:"flex-end"}}><button className="btn primary" disabled={loading||!poId} onClick={reconcile}>{loading?"Checking…":"Reconcile"}</button></div></div></section>
 {result&&<section className="card"><div className="section-title"><span>{result.purchaseOrderNumber||"Purchase Order"}</span><span className={`status ${statusClass(String(result.status||""))}`}>{String(result.status||"").replaceAll("_"," ")}</span></div><div className="detail-grid"><div className="detail-field"><span>PO Value</span><strong>{Number(result.poValue||0).toFixed(2)}</strong></div><div className="detail-field"><span>Received Value</span><strong>{Number(result.receivedValue||0).toFixed(2)}</strong></div><div className="detail-field"><span>Invoiced Value</span><strong>{Number(result.invoicedValue||0).toFixed(2)}</strong></div><div className="detail-field"><span>GR/IR Balance</span><strong>{Number(result.grIrBalance||0).toFixed(2)}</strong></div><div className="detail-field"><span>Control Status</span><strong>{String(result.status||"").replaceAll("_"," ")}</strong></div><div className="detail-field"><span>Remarks</span><strong>{result.remarks||"—"}</strong></div></div><div style={{padding:"0 24px 22px"}}><button className="btn mustard" disabled={loading||String(result.status||"").includes("CLOSED")||String(result.status||"").includes("EXCEPTION")} onClick={close}>Close GR/IR</button></div></section>}
 </div>;
}
