"use client";import{useEffect,useState}from"react";import{masterDataApi,procurementApi,warehouseExecutionApi}from"@/lib/api";
export default function PutAway(){
 const[p,setP]=useState<any[]>([]),[receipts,setReceipts]=useState<any[]>([]),[w,setW]=useState<any[]>([]),[bins,setBins]=useState<any[]>([]),[receiptId,setReceiptId]=useState(""),[warehouseId,setWarehouseId]=useState(""),[fromBin,setFromBin]=useState(""),[selected,setSelected]=useState<any|null>(null),[lines,setLines]=useState<any[]>([]),[lineBin,setLineBin]=useState<Record<string,string>>({}),[lineQty,setLineQty]=useState<Record<string,string>>({}),[busy,setBusy]=useState(false),[error,setError]=useState(""),[message,setMessage]=useState("");
 const load=async()=>{try{const[a,b,c]=await Promise.all([warehouseExecutionApi.putAways(),masterDataApi.warehouses(),procurementApi.goodsReceipts()]);setP(a);setW(b);setReceipts(c)}catch(e:any){setError(e.message||"Unable to load put-away.")}};
 useEffect(()=>{load()},[]);
 useEffect(()=>{if(warehouseId)warehouseExecutionApi.bins(warehouseId).then(setBins).catch(()=>setBins([]));else setBins([])},[warehouseId]);
 const act=async(fn:any,msg:string)=>{setBusy(true);setError("");setMessage("");try{await fn();setMessage(msg);await load()}catch(e:any){setError(e.message||"Operation failed.")}finally{setBusy(false)}};
 const create=()=>act(()=>warehouseExecutionApi.createPutAway({goodsReceiptId:receiptId,fromBinId:fromBin,remarks:"Warehouse put-away"}),"Put-away created.");
 const work=async(x:any)=>{setSelected(x);setError("");try{const l=await warehouseExecutionApi.putAwayLines(x.id);setLines(l);setWarehouseId(x.warehouseId||"");}catch(e:any){setError(e.message||"Unable to load put-away lines.")}};
 const executeLine=async(l:any)=>{const q=Number(lineQty[l.id]||0),b=lineBin[l.id];if(!b||q<=0){setError("Select a destination bin and enter a positive quantity.");return}await act(()=>warehouseExecutionApi.putAwayLine(l.id,{toBinId:b,quantity:q,remarks:"Warehouse put-away"}),"Put-away line processed.");if(selected)await work(selected)};
 return <main className="content"><div className="page-head"><div><div className="eyebrow">WAREHOUSE / PUT-AWAY</div><h1>Put-Away</h1><p>Move accepted goods from the receiving bin into storage bins with line-level execution.</p></div></div>{(error||message)&&<div className={error?"alert error":"alert success"}>{error||message}</div>}
 <section className="card"><div className="section-title">Create Put-Away</div><div className="warehouse-form-grid">
  <div className="form-field"><label>Goods Receipt</label><select className="form-input" value={receiptId} onChange={e=>{setReceiptId(e.target.value);const x=receipts.find(r=>r.id===e.target.value);setWarehouseId(x?.warehouseId||x?.warehouse?.id||"")}}><option value="">Select approved goods receipt</option>{receipts.filter(x=>x.status==="APPROVED").map(x=><option key={x.id} value={x.id}>{x.grnNumber||x.receiptNumber||x.id}</option>)}</select></div>
  <div className="form-field"><label>Warehouse</label><select className="form-input" value={warehouseId} onChange={e=>setWarehouseId(e.target.value)}><option value="">Select</option>{w.map(x=><option key={x.id} value={x.id}>{x.code} — {x.name}</option>)}</select></div>
  <div className="form-field"><label>Receiving / staging bin</label><select className="form-input" value={fromBin} onChange={e=>setFromBin(e.target.value)}><option value="">Select receiving bin</option>{bins.filter(b=>b.receivingBin).map(b=><option key={b.id} value={b.id}>{b.code} — {b.name}</option>)}</select></div>
  <div className="warehouse-form-actions"><button className="btn primary" disabled={busy||!receiptId||!fromBin} onClick={create}>Create Put-Away</button></div>
 </div></section>
 <section className="card" style={{marginTop:18}}><div className="table-wrap"><table className="table"><thead><tr><th>Put-Away</th><th>GRN</th><th>Warehouse</th><th>Status</th><th>Lines</th><th>Actions</th></tr></thead><tbody>{p.map(x=><tr key={x.id}><td>{x.putAwayNumber||x.id}</td><td>{x.grnNumber||"—"}</td><td>{x.warehouseCode||"—"}</td><td>{x.status}</td><td>{x.lines?.length||0}</td><td className="actions"><button className="btn" onClick={()=>work(x)}>Work Lines</button><button className="btn" disabled={busy} onClick={()=>act(()=>warehouseExecutionApi.completePutAway(x.id),"Put-away completed.")}>Complete</button><button className="btn" disabled={busy} onClick={()=>act(()=>warehouseExecutionApi.cancelPutAway(x.id),"Put-away cancelled.")}>Cancel</button></td></tr>)}{!p.length&&<tr><td colSpan={6} className="empty">No put-away documents.</td></tr>}</tbody></table></div></section>
 {selected&&<section className="card" style={{marginTop:18}}><div className="section-title">Put-Away Lines — {selected.putAwayNumber||selected.id}</div><div className="table-wrap"><table className="table"><thead><tr><th>SKU</th><th>Planned</th><th>Completed</th><th>Remaining</th><th>Destination Bin</th><th>Quantity</th><th></th></tr></thead><tbody>{lines.map(l=>{const remaining=Number(l.plannedQuantity||0)-Number(l.completedQuantity||0);return <tr key={l.id}><td>{l.productSku||l.product?.sku||l.product?.name||"—"}</td><td>{l.plannedQuantity}</td><td>{l.completedQuantity}</td><td>{remaining.toFixed(2)}</td><td><select className="form-input" value={lineBin[l.id]||l.toBinId||""} onChange={e=>setLineBin({...lineBin,[l.id]:e.target.value})}><option value="">Select storage bin</option>{bins.filter(b=>!b.receivingBin).map(b=><option key={b.id} value={b.id}>{b.code} — {b.name}</option>)}</select></td><td><input className="form-input" type="number" min="0.01" max={remaining} step="0.01" value={lineQty[l.id]||remaining} onChange={e=>setLineQty({...lineQty,[l.id]:e.target.value})}/></td><td><button className="btn primary" disabled={busy||remaining<=0} onClick={()=>executeLine(l)}>Put Away</button></td></tr>})}{!lines.length&&<tr><td colSpan={7} className="empty">No lines found.</td></tr>}</tbody></table></div></section>}
 </main>}