import Link from "next/link";
import { ModuleWorkspace } from "@/components/ModuleWorkspace";

export default function ProcurementCycleClosure() {
  const rows = [
    { Document: "PO-000087", Supplier: "Supplier A", GRN: "GRN-000063", Invoice: "VINV-000019", Payment: "Pending", Status: "IN_PROGRESS", Exception: "Awaiting vendor payment" },
    { Document: "PO-000086", Supplier: "Supplier B", GRN: "GRN-000062", Invoice: "VINV-000018", Payment: "—", Status: "BLOCKED", Exception: "Invoice price variance" },
    { Document: "PO-000084", Supplier: "Supplier C", GRN: "GRN-000060", Invoice: "VINV-000017", Payment: "Paid", Status: "CLOSED", Exception: "—" },
  ];
  return <ModuleWorkspace eyebrow="PROCUREMENT / CYCLE CLOSURE" title="Procurement Cycle Closure" description="Control the post-GR procurement lifecycle: invoice verification, payment, goods issue or consumption, GR/IR reconciliation, supplier evaluation and closure." stats={[{label:"Open Procurement Cycles",value:"19",foot:"Require follow-up"},{label:"Invoice Exceptions",value:"4",foot:"3-way match queue",tone:"warning"},{label:"GR/IR Exceptions",value:"3",foot:"Reconciliation queue",tone:"warning"},{label:"Closed Cycles",value:"84",foot:"Current period",tone:"success"}]} process={[{label:"Goods Receipt",detail:"Physical receipt",status:"Complete",tone:"approved"},{label:"Invoice",detail:"3-way match",status:"4 exceptions",tone:"pending"},{label:"Payment",detail:"Vendor open item",status:"Pending",tone:"draft"},{label:"GR/IR",detail:"Reconcile balance",status:"Review",tone:"pending"},{label:"Evaluation",detail:"Supplier score",status:"Pending",tone:"draft"},{label:"Closure",detail:"Close PO cycle",status:"Open",tone:"draft"}]} columns={["Document","Supplier","GRN","Invoice","Payment","Status","Exception"]} rows={rows} searchPlaceholder="Search PO, supplier, GRN or invoice...">
    <div className="grid dashboard-grid" style={{ marginBottom: 18 }}>
      <section className="card"><div className="section-title">Post-GR Work Queues</div>{[["Goods Issues / Consumption","/procurement/goods-issues","Issue received stock to consumption, production or transfer"],["Vendor Invoice Verification","/procurement/vendor-invoices","PO + GR + invoice quantity and price matching"],["GR/IR Reconciliation","/procurement/gr-ir-reconciliation","Identify and resolve receipt/invoice differences"],["Vendor Evaluation","/procurement/vendor-evaluation","Review price, quality, delivery and service"],["Vendor Payments","/procurement/vendor-payments","Track approved vendor invoices through payment"]].map(([label,href,detail])=><div className="list-row" key={href}><div><Link className="link" href={href}>{label}</Link><div className="muted">{detail}</div></div><span className="chevron">›</span></div>)}</section>
      <section className="card"><div className="section-title">Closure Controls</div><div className="detail-grid"><div className="detail-field"><span>Financial path</span><strong>Invoice → 3-way match → Payment</strong></div><div className="detail-field"><span>Physical path</span><strong>Goods Issue / Consumption → Stock update</strong></div><div className="detail-field"><span>Control point</span><strong>GR/IR reconciliation</strong></div><div className="detail-field"><span>Supplier review</span><strong>Price · Quality · Delivery · Service</strong></div><div className="detail-field"><span>Final state</span><strong>Procurement cycle closed</strong></div></div></section>
    </div>
  </ModuleWorkspace>;
}
