package com.digipals.wms.finance.service;

import com.digipals.wms.common.exception.InvalidWorkflowException;
import com.digipals.wms.finance.dto.*;
import com.digipals.wms.finance.entity.*;
import com.digipals.wms.finance.repository.*;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import java.math.*; import java.nio.charset.StandardCharsets; import java.time.*; import java.util.*;

@Service @RequiredArgsConstructor @Transactional
public class AdvancedFinanceService {
 private final CreditProfileRepository credits; private final CollectionCaseRepository collections; private final FinanceDisputeRepository disputes;
 private final RevenueContractRepository contracts; private final RevenueObligationRepository obligations; private final RevenueRecognitionEventRepository recognition;
 private final TaxCodeRepository taxCodes; private final FxRateRepository fxRates; private final FundRepository funds; private final ProductCostEstimateRepository costs;
 private final AccrualTemplateRepository accruals; private final FinancePostingService posting;

 public CreditProfile saveCredit(CreditProfileRequest r){ CreditProfile x=credits.findByCustomerId(r.customerId()).orElseGet(CreditProfile::new); x.setCustomerId(r.customerId()); x.setCreditLimit(money(r.creditLimit())); x.setCreditScore(r.creditScore()); x.setRiskClass(r.riskClass()); x.setReviewDate(r.reviewDate()); x.setActive(true); return credits.save(x); }
 public List<CollectionCase> collectionWorklist(String status){ return status==null||status.isBlank()?collections.findAll():collections.findByStatusOrderByDueDateAsc(status.toUpperCase()); }
 public CollectionCase createCollection(CollectionCaseRequest r){ return collections.save(CollectionCase.builder().customerId(r.customerId()).invoiceReference(r.invoiceReference().trim()).dueDate(r.dueDate()).amountDue(money(r.amountDue())).priority(r.priority()==null?"NORMAL":r.priority().toUpperCase()).assignedTo(r.assignedTo()).promiseDate(r.promiseDate()).promiseAmount(r.promiseAmount()).notes(r.notes()).status("OPEN").active(true).build()); }
 public FinanceDispute createDispute(DisputeRequest r){ return disputes.save(FinanceDispute.builder().customerId(r.customerId()).invoiceReference(r.invoiceReference().trim()).reasonCode(r.reasonCode().trim()).amount(money(r.amount())).owner(r.owner()).resolution(r.resolution()).status("OPEN").active(true).build()); }
 public List<FinanceDispute> disputes(String status){ return status==null||status.isBlank()?disputes.findAll():disputes.findByStatusOrderByCreatedAtDesc(status.toUpperCase()); }
 public RevenueContract createContract(RevenueContractRequest r){ if(contracts.findByContractNumber(r.contractNumber().trim()).isPresent()) throw new InvalidWorkflowException("Revenue contract already exists."); return contracts.save(RevenueContract.builder().contractNumber(r.contractNumber().trim()).customerId(r.customerId()).contractDate(r.contractDate()).currency(currency(r.currency())).transactionPrice(money(r.transactionPrice())).status("OPEN").active(true).build()); }
 public RevenueObligation addObligation(RevenueObligationRequest r){ RevenueContract c=contracts.findById(r.contractId()).orElseThrow(()->new InvalidWorkflowException("Revenue contract not found.")); if(obligations.findByContractId(c.getId()).stream().anyMatch(x->x.getObligationCode().equalsIgnoreCase(r.obligationCode().trim()))) throw new InvalidWorkflowException("Performance obligation already exists."); return obligations.save(RevenueObligation.builder().contract(c).obligationCode(r.obligationCode().trim()).description(r.description().trim()).standalonePrice(money(r.standalonePrice())).allocatedPrice(BigDecimal.ZERO).fulfilledAmount(BigDecimal.ZERO).status("OPEN").active(true).build()); }
 public List<RevenueObligation> obligations(UUID contractId){ return obligations.findByContractId(contractId); }
 public RevenueRecognitionEvent recognize(RecognitionRequest r){ RevenueObligation o=obligations.findById(r.obligationId()).orElseThrow(()->new InvalidWorkflowException("Performance obligation not found.")); BigDecimal remaining=o.getAllocatedPrice().subtract(o.getFulfilledAmount()).max(BigDecimal.ZERO); if(o.getAllocatedPrice().compareTo(BigDecimal.ZERO)==0) throw new InvalidWorkflowException("Allocate the contract transaction price before recognition."); BigDecimal amount=money(r.amount()); if(amount.compareTo(remaining)>0) throw new InvalidWorkflowException("Recognition exceeds remaining allocated performance obligation."); if(recognition.existsByObligationIdAndEventDateAndRecognitionType(o.getId(),r.eventDate(),r.recognitionType().trim())) throw new InvalidWorkflowException("Recognition event already posted for this date and type."); UUID ref=UUID.nameUUIDFromBytes(("RAR:"+o.getId()+":"+r.eventDate()+":"+r.recognitionType()).getBytes(StandardCharsets.UTF_8)); AccountingDocument doc=posting.postBalanced("REVENUE_RECOGNITION","RAR",ref,o.getContract().getContractNumber(),"USD","Revenue recognition "+o.getObligationCode(),List.of(new FinancePostingService.PostingLine("120000",amount,BigDecimal.ZERO,null,null,null,null,"Contract asset / receivable"),new FinancePostingService.PostingLine("400000",BigDecimal.ZERO,amount,null,null,null,null,"Recognized revenue"))); o.setFulfilledAmount(o.getFulfilledAmount().add(amount)); if(o.getFulfilledAmount().compareTo(o.getAllocatedPrice())>=0)o.setStatus("FULFILLED"); obligations.save(o); return recognition.save(RevenueRecognitionEvent.builder().obligation(o).eventDate(r.eventDate()).amount(amount).recognitionType(r.recognitionType().trim()).accountingDocumentId(doc.getId()).build()); }
 public TaxCode saveTaxCode(TaxCodeRequest r){ TaxCode x=taxCodes.findByTaxCode(r.taxCode().trim().toUpperCase()).orElseGet(TaxCode::new); x.setTaxCode(r.taxCode().trim().toUpperCase());x.setDescription(r.description().trim());x.setRate(r.rate());x.setInputAccountCode(r.inputAccountCode());x.setOutputAccountCode(r.outputAccountCode());x.setWithholding(r.withholding());x.setActive(true);return taxCodes.save(x); }
 public BigDecimal calculateTax(String code,BigDecimal taxable){ TaxCode t=taxCodes.findByTaxCode(code.trim().toUpperCase()).orElseThrow(()->new InvalidWorkflowException("Tax code not found.")); return taxable.multiply(t.getRate()).divide(BigDecimal.valueOf(100),2,RoundingMode.HALF_UP); }
 public FxRate saveFxRate(FxRateRequest r){ if(r.fromCurrency().equalsIgnoreCase(r.toCurrency()))throw new InvalidWorkflowException("FX currencies must differ."); return fxRates.save(FxRate.builder().rateDate(r.rateDate()).fromCurrency(currency(r.fromCurrency())).toCurrency(currency(r.toCurrency())).rate(r.rate).source(r.source()==null?"MANUAL":r.source().trim()).build()); }
 public List<FxRate> fxRates(LocalDate date){return fxRates.findAll().stream().filter(x->date==null||x.getRateDate().equals(date)).toList();}
 public Fund saveFund(FundRequest r){ Fund f=funds.findByFundCode(r.fundCode().trim()).orElseGet(Fund::new);f.setFundCode(r.fundCode().trim());f.setFundName(r.fundName().trim());f.setCurrency(currency(r.currency()));f.setBudgetAmount(money(r.budgetAmount()));f.setActive(true);return funds.save(f); }
 public ProductCostEstimate createCost(CostEstimateRequest r){BigDecimal total=money(r.materialCost()).add(money(r.laborCost())).add(money(r.overheadCost()));return costs.save(ProductCostEstimate.builder().productCode(r.productCode().trim()).costingDate(r.costingDate()).materialCost(r.materialCost()).laborCost(r.laborCost()).overheadCost(r.overheadCost()).standardCost(total).status("CREATED").build());}
 public ProductCostEstimate releaseCost(UUID id){ProductCostEstimate x=costs.findById(id).orElseThrow(()->new InvalidWorkflowException("Cost estimate not found."));x.setStatus("RELEASED");x.setReleasedAt(LocalDateTime.now());return costs.save(x);}
 public AccrualTemplate createAccrual(AccrualTemplateRequest r){return accruals.save(AccrualTemplate.builder().templateCode(r.templateCode().trim()).description(r.description().trim()).expenseAccountCode(r.expenseAccountCode().trim()).liabilityAccountCode(r.liabilityAccountCode().trim()).amount(money(r.amount())).costCenterCode(r.costCenterCode()).frequency("MONTHLY").nextRunDate(r.nextRunDate()==null?LocalDate.now().withDayOfMonth(1):r.nextRunDate()).active(true).build());}
 private String currency(String x){String c=x==null||x.isBlank()?"USD":x.trim().toUpperCase();if(!c.matches("[A-Z]{3}"))throw new InvalidWorkflowException("Currency must be a 3-letter ISO code.");return c;}
 private BigDecimal money(BigDecimal x){if(x==null||x.compareTo(BigDecimal.ZERO)<0)throw new InvalidWorkflowException("Amount must be zero or greater.");return x.setScale(2,RoundingMode.HALF_UP);}
}