"use client";
import {useEffect,useState} from "react";
import {financeApi} from "@/lib/api";

export default function FinanceControls(){
 const[costCenters,setCostCenters]=useState<any[]>([]),[banks,setBanks]=useState<any[]>([]),[assets,setAssets]=useState<any[]>([]);
 const[message,setMessage]=useState("");
 const[cc,setCc]=useState({code:"",name:"",responsiblePerson:""});
 const[bank,setBank]=useState({accountNumber:"",bankName:"",branchName:"",currency:"USD",glAccountCode:"100000"});
 const[asset,setAsset]=useState({assetNumber:"",assetName:"",assetClass:"",acquisitionDate:"",acquisitionCost:"",usefulLifeMonths:"60",residualValue:"0",costCenterCode:""});
 const load=()=>Promise.all([financeApi.costCenters(),financeApi.bankAccounts(),financeApi.fixedAssets()]).then(([a,b,c])=>{setCostCenters(a);setBanks(b);setAssets(c)}).catch(e=>setMessage(e.message||"Unable to load finance controls."));
 useEffect(load,[]);
 const createCc=async()=>{try{await financeApi.createCostCenter(cc);setCc({code:"",name:"",responsiblePerson:""});await load();setMessage("Cost centre created.")}catch(e:any){setMessage(e.message)}};
 const createBank=async()=>{try{await financeApi.createBankAccount(bank);await load();setMessage("Bank account created.")}catch(e:any){setMessage(e.message)}};
 const createAsset=async()=>{try{await financeApi.createFixedAsset({...asset,acquisitionCost:Number(asset.acquisitionCost),usefulLifeMonths:Number(asset.usefulLifeMonths),residualValue:Number(asset.residualValue)});setAsset({...asset,assetNumber:"",assetName:"",acquisitionCost:""});await load();setMessage("Fixed asset created.")}catch(e:any){setMessage(e.message)}};
 return <div className="content"><div className="page-head"><div><div className="eyebrow">FINANCE / CONTROLLING</div><h1>Finance Controls</h1><p>Cost centres, bank accounts and fixed assets supporting the finance lifecycle.</p></div><button className="btn" onClick={load}>Refresh</button></div>{message&&<div className="alert">{message}</div>}
 <section className="card form-card"><div className="section-title">Cost Centres</div><div className="form-grid"><input className="form-input" placeholder="Code" value={cc.code} onChange={e=>setCc({...cc,code:e.target.value})}/><input className="form-input" placeholder="Name" value={cc.name} onChange={e=>setCc({...cc,name:e.target.value})}/><input className="form-input" placeholder="Responsible person" value={cc.responsiblePerson} onChange={e=>setCc({...cc,responsiblePerson:e.target.value})}/><button className="btn primary" onClick={createCc}>Create Cost Centre</button></div><div className="table-wrap"><table className="table"><thead><tr><th>Code</th><th>Name</th><th>Responsible</th></tr></thead><tbody>{costCenters.map(x=><tr key={x.id}><td>{x.code}</td><td>{x.name}</td><td>{x.responsiblePerson||"—"}</td></tr>)}</tbody></table></div></section>
 <section className="card form-card"><div className="section-title">Bank Accounts</div><div className="form-grid"><input className="form-input" placeholder="Account number" value={bank.accountNumber} onChange={e=>setBank({...bank,accountNumber:e.target.value})}/><input className="form-input" placeholder="Bank name" value={bank.bankName} onChange={e=>setBank({...bank,bankName:e.target.value})}/><input className="form-input" placeholder="Branch" value={bank.branchName} onChange={e=>setBank({...bank,branchName:e.target.value})}/><select className="form-input" value={bank.currency} onChange={e=>setBank({...bank,currency:e.target.value})}><option>USD</option><option>ZWL</option></select><select className="form-input" value={bank.glAccountCode} onChange={e=>setBank({...bank,glAccountCode:e.target.value})}><option>100000</option></select><button className="btn primary" onClick={createBank}>Create Bank Account</button></div><div className="table-wrap"><table className="table"><thead><tr><th>Account</th><th>Bank</th><th>Branch</th><th>Currency</th><th>G/L</th></tr></thead><tbody>{banks.map(x=><tr key={x.id}><td>{x.accountNumber}</td><td>{x.bankName}</td><td>{x.branchName||"—"}</td><td>{x.currency}</td><td>{x.glAccountCode}</td></tr>)}</tbody></table></div></section>
 <section className="card form-card"><div className="section-title">Fixed Assets</div><div className="form-grid"><input className="form-input" placeholder="Asset number" value={asset.assetNumber} onChange={e=>setAsset({...asset,assetNumber:e.target.value})}/><input className="form-input" placeholder="Asset name" value={asset.assetName} onChange={e=>setAsset({...asset,assetName:e.target.value})}/><input className="form-input" placeholder="Asset class" value={asset.assetClass} onChange={e=>setAsset({...asset,assetClass:e.target.value})}/><input className="form-input" type="date" value={asset.acquisitionDate} onChange={e=>setAsset({...asset,acquisitionDate:e.target.value})}/><input className="form-input" type="number" placeholder="Acquisition cost" value={asset.acquisitionCost} onChange={e=>setAsset({...asset,acquisitionCost:e.target.value})}/><input className="form-input" type="number" placeholder="Useful life months" value={asset.usefulLifeMonths} onChange={e=>setAsset({...asset,usefulLifeMonths:e.target.value})}/><input className="form-input" type="number" placeholder="Residual value" value={asset.residualValue} onChange={e=>setAsset({...asset,residualValue:e.target.value})}/><input className="form-input" placeholder="Cost centre" value={asset.costCenterCode} onChange={e=>setAsset({...asset,costCenterCode:e.target.value})}/><button className="btn primary" onClick={createAsset}>Create Asset</button></div><div className="table-wrap"><table className="table"><thead><tr><th>Asset</th><th>Name</th><th>Class</th><th>Cost</th><th>Accum. Depreciation</th><th>Book Value</th><th>Status</th><th></th></tr></thead><tbody>{assets.map(x=><tr key={x.id}><td>{x.assetNumber}</td><td>{x.assetName}</td><td>{x.assetClass}</td><td>{Number(x.acquisitionCost||0).toFixed(2)}</td><td>{Number(x.accumulatedDepreciation||0).toFixed(2)}</td><td>{(Number(x.acquisitionCost||0)-Number(x.accumulatedDepreciation||0)).toFixed(2)}</td><td>{x.status}</td><td><button className="btn" disabled={x.status==="FULLY_DEPRECIATED"} onClick={async()=>{await financeApi.depreciateAsset(x.id);await load();}}>Post Monthly Depreciation</button></td></tr>)}</tbody></table></div></section>
 </div>
}