package com.digipals.wms.manufacturing.service;
import com.digipals.wms.common.exception.InvalidWorkflowException;
import com.digipals.wms.common.exception.ResourceNotFoundException;
import com.digipals.wms.integration.IntegrationEventTypes;
import com.digipals.wms.integration.outbox.IntegrationOutboxService;
import com.digipals.wms.manufacturing.entity.*;
import com.digipals.wms.manufacturing.repository.*;
import com.digipals.wms.products.Product;
import com.digipals.wms.products.ProductRepository;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import java.math.BigDecimal; import java.time.*; import java.util.*;
@Service @RequiredArgsConstructor @Transactional
public class ManufacturingServiceImpl implements ManufacturingService {
 private final ProductRepository products; private final BomRepository boms; private final RoutingRepository routings; private final ProductionOrderRepository orders; private final ProductionConfirmationRepository confirmations; private final CapacityRecordRepository capacities; private final MrpPlanRepository mrps; private final KanbanControlCycleRepository cycles; private final KanbanSignalRepository signals; private final IntegrationOutboxService outbox;
 public Bom createBom(Bom b){if(b.getProduct()==null||b.getProduct().getId()==null)throw new InvalidWorkflowException("BOM product is required.");if(b.getBomNumber()==null||b.getBomNumber().isBlank())b.setBomNumber("BOM-"+UUID.randomUUID().toString().substring(0,8).toUpperCase());b.setStatus("ACTIVE");int seq=1;for(BomItem i:b.getItems()){i.setBom(b);i.setSequenceNo(i.getSequenceNo()==null?seq:i.getSequenceNo());seq++;if(i.getQuantity()==null||i.getQuantity().signum()<=0)throw new InvalidWorkflowException("BOM component quantity must be greater than zero.");}return boms.save(b);}
 public Routing createRouting(Routing r){if(r.getProduct()==null||r.getProduct().getId()==null)throw new InvalidWorkflowException("Routing product is required.");if(r.getRoutingNumber()==null||r.getRoutingNumber().isBlank())r.setRoutingNumber("RTG-"+UUID.randomUUID().toString().substring(0,8).toUpperCase());r.setStatus("ACTIVE");int seq=10;for(RoutingOperation o:r.getOperations()){o.setRouting(r);if(o.getOperationNo()==null)o.setOperationNo(seq);seq+=10;}return routings.save(r);}
 public ProductionOrder createProductionOrder(UUID productId,String plant,String type,BigDecimal qty,LocalDate start,LocalDate finish){Product p=products.findById(productId).orElseThrow(()->new ResourceNotFoundException("Product not found."));if(qty==null||qty.signum()<=0)throw new InvalidWorkflowException("Production quantity must be greater than zero.");Bom bom=boms.findFirstByProductIdAndPlantCodeAndStatusOrderByCreatedAtDesc(productId,plant,"ACTIVE").orElse(null);Routing routing=routings.findFirstByProductIdAndPlantCodeAndStatusOrderByCreatedAtDesc(productId,plant,"ACTIVE").orElse(null);ProductionOrder o=orders.save(ProductionOrder.builder().orderNumber("MO-"+UUID.randomUUID().toString().substring(0,10).toUpperCase()).product(p).bom(bom).routing(routing).plantCode(plant).plannedQuantity(qty).confirmedQuantity(BigDecimal.ZERO).orderType(type==null?"DISCRETE":type.toUpperCase()).status("CREATED").plannedStartDate(start).plannedFinishDate(finish).build());if(bom!=null)for(BomItem i:bom.getItems())o.getMaterials().add(ProductionOrderMaterial.builder().productionOrder(o).componentProduct(i.getComponentProduct()).requiredQuantity(i.getQuantity().multiply(qty)).issuedQuantity(BigDecimal.ZERO).build());return orders.save(o);}
 public ProductionOrder releaseProductionOrder(UUID id){ProductionOrder o=orders.findById(id).orElseThrow(()->new ResourceNotFoundException("Production order not found."));if(!"CREATED".equals(o.getStatus()))throw new InvalidWorkflowException("Only created production orders can be released.");if(o.getBom()==null)throw new InvalidWorkflowException("Active BOM is required before release.");o.setStatus("RELEASED");return o;}
 public ProductionConfirmation confirmProduction(UUID id,BigDecimal qty,BigDecimal scrap,String operation,String remarks){ProductionOrder o=orders.findById(id).orElseThrow(()->new ResourceNotFoundException("Production order not found."));if(!Set.of("RELEASED","IN_PROCESS").contains(o.getStatus()))throw new InvalidWorkflowException("Production order must be released before confirmation.");if(qty==null||qty.signum()<=0)throw new InvalidWorkflowException("Confirmation quantity must be greater than zero.");if(scrap==null||scrap.signum()<0)throw new InvalidWorkflowException("Scrap quantity cannot be negative.");BigDecimal total=o.getConfirmedQuantity().add(qty);if(total.compareTo(o.getPlannedQuantity())>0)throw new InvalidWorkflowException("Confirmed quantity cannot exceed planned quantity.");ProductionConfirmation c=confirmations.save(ProductionConfirmation.builder().productionOrder(o).quantity(qty).scrapQuantity(scrap).confirmationTime(LocalDateTime.now()).operation(operation).remarks(remarks).build());o.setConfirmedQuantity(total);o.setStatus(total.compareTo(o.getPlannedQuantity())==0?"CONFIRMED":"IN_PROCESS");orders.save(o);outbox.enqueue(IntegrationEventTypes.MANUFACTURING_PRODUCTION_CONFIRMED,"PRODUCTION_ORDER",o.getId(),new com.digipals.wms.integration.manufacturing.ProductionConfirmedEvent(o.getId(),o.getOrderNumber(),o.getProduct().getSku(),qty,scrap,qty.multiply(o.getProduct().getCostPrice()==null?BigDecimal.ZERO:o.getProduct().getCostPrice()),"USD",LocalDateTime.now()),LocalDateTime.now());return c;}
 public CapacityRecord saveCapacity(CapacityRecord r){if(r.getAvailableMinutes()==null||r.getAvailableMinutes().signum()<0||r.getPlannedMinutes()==null||r.getPlannedMinutes().signum()<0)throw new InvalidWorkflowException("Capacity values cannot be negative.");return capacities.save(r);}
 public MrpPlan runMrp(String plant,String strategy,int demand,int planned){if(demand<0||planned<0)throw new InvalidWorkflowException("MRP counts cannot be negative.");return mrps.save(MrpPlan.builder().plantCode(plant).strategyGroup(strategy).runTime(LocalDateTime.now()).status("COMPLETED").demandCount(demand).plannedOrderCount(planned).build());}
 public KanbanSignal signalKanban(UUID cycleId,String trigger){KanbanControlCycle c=cycles.findById(cycleId).orElseThrow(()->new ResourceNotFoundException("Kanban control cycle not found."));return signals.save(KanbanSignal.builder().controlCycle(c).status("WAITING_REPLENISHMENT").triggerSource(trigger==null?"MANUAL":trigger).build());}
}