package com.digipals.wms.quality.service;
import com.digipals.wms.common.exception.InvalidWorkflowException;
import com.digipals.wms.common.exception.ResourceNotFoundException;
import com.digipals.wms.products.Product;
import com.digipals.wms.products.ProductRepository;
import com.digipals.wms.inventory.service.InventoryService;
import com.digipals.wms.bin.entity.Bin;
import com.digipals.wms.bin.repository.BinRepository;
import com.digipals.wms.warehouse.repository.WarehouseRepository;
import com.digipals.wms.quality.entity.*;
import com.digipals.wms.quality.repository.*;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.*;
@Service @RequiredArgsConstructor @Transactional
public class QualityManagementServiceImpl implements QualityManagementService {
 private final ProductRepository products; private final MasterInspectionCharacteristicRepository characteristics; private final InspectionPlanRepository plans; private final InspectionLotRepository lots; private final InspectionResultRepository results; private final UsageDecisionRepository decisions; private final QualityNotificationRepository notifications; private final QualityCatalogCodeRepository catalogCodes; private final QualityInfoRecordRepository qualityInfoRecords; private final InventoryService inventoryService; private final BinRepository binRepository; private final WarehouseRepository warehouseRepository;
 public MasterInspectionCharacteristic createCharacteristic(MasterInspectionCharacteristic c){ if(c.getCode()==null||c.getCode().isBlank())throw new InvalidWorkflowException("Characteristic code is required."); if(characteristics.findByCodeIgnoreCase(c.getCode()).isPresent())throw new InvalidWorkflowException("Characteristic code already exists."); return characteristics.save(c); }
 public InspectionPlan createPlan(InspectionPlan p,List<UUID> ids){ if(p.getProduct()==null||p.getProduct().getId()==null)throw new InvalidWorkflowException("Product is required."); if(plans.findByPlanNumber(p.getPlanNumber()).isPresent())throw new InvalidWorkflowException("Inspection plan number already exists."); p.setStatus("ACTIVE"); int seq=1; for(UUID id:ids){MasterInspectionCharacteristic c=characteristics.findById(id).orElseThrow(()->new ResourceNotFoundException("Inspection characteristic not found: "+id)); p.getCharacteristics().add(InspectionPlanCharacteristic.builder().plan(p).characteristic(c).sampleSize(1).sequenceNo(seq++).build());} return plans.save(p); }
 public InspectionLot createLot(UUID productId,String plant,String type,String sourceType,UUID sourceId,BigDecimal quantity){Product p=products.findById(productId).orElseThrow(()->new ResourceNotFoundException("Product not found.")); if(quantity==null||quantity.signum()<=0)throw new InvalidWorkflowException("Inspection quantity must be greater than zero."); String no="IL-"+UUID.randomUUID().toString().substring(0,10).toUpperCase(); return lots.save(InspectionLot.builder().lotNumber(no).inspectionType(type).product(p).plantCode(plant).sourceDocumentType(sourceType).sourceDocumentId(sourceId).quantity(quantity).status("OPEN").createdOn(LocalDateTime.now()).build());}
 public InspectionResult recordResult(UUID lotId,UUID characteristicId,BigDecimal measured,String qualitative){InspectionLot lot=lots.findById(lotId).orElseThrow(()->new ResourceNotFoundException("Inspection lot not found.")); if(!"OPEN".equals(lot.getStatus())&&!"RESULTS_RECORDED".equals(lot.getStatus()))throw new InvalidWorkflowException("Inspection lot is not open for results."); MasterInspectionCharacteristic c=characteristics.findById(characteristicId).orElseThrow(()->new ResourceNotFoundException("Characteristic not found.")); String status="PASS"; if(measured!=null){if(c.getLowerTolerance()!=null&&measured.compareTo(c.getLowerTolerance())<0)status="FAIL";if(c.getUpperTolerance()!=null&&measured.compareTo(c.getUpperTolerance())>0)status="FAIL";} if(qualitative!=null&&!qualitative.isBlank()&&!qualitative.equalsIgnoreCase("PASS")&&!qualitative.equalsIgnoreCase("OK"))status="FAIL"; InspectionResult r=results.save(InspectionResult.builder().inspectionLot(lot).characteristic(c).measuredValue(measured).qualitativeResult(qualitative).resultStatus(status).build()); lot.setStatus("RESULTS_RECORDED"); return r;}
 public UsageDecision decide(UUID lotId,String decision,String stockAction,String remarks,UUID binId){InspectionLot lot=lots.findById(lotId).orElseThrow(()->new ResourceNotFoundException("Inspection lot not found.")); if("CLOSED".equals(lot.getStatus()))throw new InvalidWorkflowException("Inspection lot is already closed."); List<InspectionResult> rs=results.findByInspectionLotId(lotId); if(rs.isEmpty())throw new InvalidWorkflowException("Results must be recorded before usage decision."); String code=decision.trim().toUpperCase(); if(!Set.of("ACCEPT","REJECT","CONDITIONAL").contains(code))throw new InvalidWorkflowException("Invalid usage decision."); String action=stockAction==null?("ACCEPT".equals(code)?"RELEASE":"BLOCK"):stockAction.toUpperCase(); if(binId!=null){Bin bin=binRepository.findById(binId).orElseThrow(()->new ResourceNotFoundException("Inspection stock bin not found."));var wh=warehouseRepository.findByCode(lot.getPlantCode()).orElseThrow(()->new ResourceNotFoundException("Plant warehouse not found."));if("ACCEPT".equals(code)||"RELEASE".equals(action)) inventoryService.releaseQualityStock(wh,bin,lot.getProduct(),lot.getQuantity(),lot.getLotNumber(),"QM_USAGE_DECISION",remarks,null); else if("REJECT".equals(code)||"BLOCK".equals(action)) inventoryService.blockQualityStock(wh,bin,lot.getProduct(),lot.getQuantity(),lot.getLotNumber(),"QM_USAGE_DECISION",remarks,null); } UsageDecision d=decisions.save(UsageDecision.builder().inspectionLot(lot).decisionCode(code).stockAction(action).remarks(remarks).build()); lot.setStatus("CLOSED"); return d;}
 public QualityNotification completeTask(UUID notificationId,UUID taskId,String notes){QualityNotification n=notifications.findById(notificationId).orElseThrow(()->new ResourceNotFoundException("Quality notification not found."));QualityNotificationTask task=n.getTasks().stream().filter(t->taskId.equals(t.getId())).findFirst().orElseThrow(()->new ResourceNotFoundException("Quality task not found."));task.setStatus("COMPLETED");task.setCompletionNotes(notes);return notifications.save(n);}
 public QualityNotification closeNotification(UUID notificationId){QualityNotification n=notifications.findById(notificationId).orElseThrow(()->new ResourceNotFoundException("Quality notification not found."));if(n.getTasks().stream().anyMatch(t->!"COMPLETED".equalsIgnoreCase(t.getStatus())))throw new InvalidWorkflowException("All quality notification tasks must be completed before closure.");n.setStatus("CLOSED");return notifications.save(n);}
 public QualityInfoRecord createQualityInfoRecord(QualityInfoRecord r){if(r.getSupplier()==null||r.getProduct()==null)throw new InvalidWorkflowException("Supplier and product are required.");if(qualityInfoRecords.findBySupplierIdAndProductId(r.getSupplier().getId(),r.getProduct().getId()).isPresent())throw new InvalidWorkflowException("Quality information record already exists.");if(r.getInspectionRequired()==null)r.setInspectionRequired(true);return qualityInfoRecords.save(r);}
 public QualityInfoRecord getQualityInfoRecord(UUID supplierId,UUID productId){return qualityInfoRecords.findBySupplierIdAndProductId(supplierId,productId).orElseThrow(()->new ResourceNotFoundException("Quality information record not found."));}
 public QualityCatalogCode createCatalogCode(QualityCatalogCode c){if(c.getCatalogType()==null||c.getCode()==null||c.getDescription()==null)throw new InvalidWorkflowException("Catalog type, code and description are required.");return catalogCodes.save(c);} @Transactional(readOnly=true) public List<QualityCatalogCode> catalog(String type){return catalogCodes.findByCatalogTypeIgnoreCase(type);}
 public QualityNotification createNotification(QualityNotification n){if(n.getNotificationNumber()==null||n.getNotificationNumber().isBlank())n.setNotificationNumber("QN-"+UUID.randomUUID().toString().substring(0,10).toUpperCase());if(n.getStatus()==null)n.setStatus("OPEN");for(QualityNotificationItem i:n.getItems())i.setNotification(n);for(QualityNotificationTask t:n.getTasks())t.setNotification(n);return notifications.save(n);}
 @Transactional(readOnly=true) public List<InspectionLot> openLots(){return lots.findByStatusOrderByCreatedAtAsc("OPEN");}
}