package com.digipals.wms.integration;

public final class IntegrationEventTypes {
    private IntegrationEventTypes() {}

    public static final String PROCUREMENT_GOODS_RECEIPT_APPROVED = "PROCUREMENT.GOODS_RECEIPT_APPROVED";
    public static final String PROCUREMENT_VENDOR_INVOICE_MATCHED = "PROCUREMENT.VENDOR_INVOICE_MATCHED";
    public static final String PROCUREMENT_VENDOR_PAYMENT_POSTED = "PROCUREMENT.VENDOR_PAYMENT_POSTED";

    public static final String INVENTORY_GOODS_ISSUE_POSTED = "INVENTORY.GOODS_ISSUE_POSTED";
    public static final String INVENTORY_STOCK_ADJUSTMENT_POSTED = "INVENTORY.STOCK_ADJUSTMENT_POSTED";

    public static final String O2C_CUSTOMER_BILLING_POSTED = "O2C.CUSTOMER_BILLING_POSTED";
    public static final String O2C_INCOMING_PAYMENT_RECEIVED = "O2C.INCOMING_PAYMENT_RECEIVED";
    public static final String O2C_INCOMING_PAYMENT_CANCELLED = "O2C.INCOMING_PAYMENT_CANCELLED";
    public static final String O2C_CASH_APPLICATION_POSTED = "O2C.CASH_APPLICATION_POSTED";
}
