"use client";
import {useEffect,useState} from "react";
import {orderToCashApi} from "@/lib/api";

const statusClass=(s:string)=>{const v=s.toLowerCase();if(v.includes("goods")||v.includes("delivered")||v.includes("complete"))return"approved";if(v.includes("pick")||v.includes("ready"))return"pending";if(v.includes("error")||v.includes("cancel"))return"blocked";return"draft"};

export default function Deliveries(){
 const [rows,setRows]=useState<any[]>([]);const [loading,setLoading]=useState(true);const [busy,setBusy]=useState("");const [message,setMessage]=useState("");
 const load=()=>{setLoading(true);orderToCashApi.deliveries().then(setRows).catch(()=>setRows([])).finally(()=>setLoading(false));};useEffect(load,[]);
 const act=async(id:string,action:string)=>{setBusy(id+action);setMessage("");try{if(action==="pick")await orderToCashApi.startPicking(id);if(action==="confirmPick")await orderToCashApi.confirmPicking(id);if(action==="pack")await orderToCashApi.confirmPacking(id);if(action==="gi")await orderToCashApi.postGoodsIssue(id);load();}catch(e){setMessage(e instanceof Error?e.message:"Delivery action failed.");}finally{setBusy("");}};
 return <div className="content"><div className="page-head"><div><div className="eyebrow">ORDER TO CASH / LOGISTICS</div><h1>Deliveries</h1><p>Execute outbound fulfilment from sales order through picking, packing and post goods issue.</p></div></div>{message&&<div className="alert error">{message}</div>}
 <section className="card"><div className="table-caption"><strong>Outbound Deliveries ({rows.length})</strong><span>{loading?"Loading live deliveries":"Live backend records"}</span></div><div className="table-wrap"><table className="table"><thead><tr><th>Delivery</th><th>Sales Order</th><th>Customer</th><th>Shipping Point</th><th>Status</th><th>Actions</th></tr></thead><tbody>{rows.map(r=>{const s=String(r.status||"");return <tr key={r.id}><td className="link">{r.deliveryNumber||r.id}</td><td>{r.salesOrderNumber||"—"}</td><td>{r.customerCode||"—"}</td><td>{r.shippingPoint||"—"}</td><td><span className={`status ${statusClass(s)}`}>{s.replaceAll("_"," ")}</span></td><td><div className="actions">{s==="READY"&&<button className="btn" disabled={!!busy} onClick={()=>act(r.id,"pick")}>{busy===r.id+"pick"?"Starting…":"Start Picking"}</button>}{s==="PICKING"&&<button className="btn" disabled={!!busy} onClick={()=>act(r.id,"confirmPick")}>Confirm Picking</button>}{s==="PICKED"&&<button className="btn" disabled={!!busy} onClick={()=>act(r.id,"pack")}>Confirm Packing</button>}{s==="PACKED"&&<button className="btn mustard" disabled={!!busy} onClick={()=>act(r.id,"gi")}>Post Goods Issue</button>}</div></td></tr>})}{!rows.length&&!loading&&<tr><td colSpan={6} className="empty">No outbound deliveries found.</td></tr>}</tbody></table></div></section></div>;
}
