"use client";
import Link from "next/link";
import {useEffect,useState} from "react";
import {orderToCashApi} from "@/lib/api";

export default function AccountsReceivable(){
 const [invoices,setInvoices]=useState<any[]>([]);const [payments,setPayments]=useState<any[]>([]);const [loading,setLoading]=useState(true);
 useEffect(()=>{Promise.all([orderToCashApi.billingDocuments(),orderToCashApi.incomingPayments()]).then(([i,p])=>{setInvoices(i);setPayments(p);}).catch(()=>{}).finally(()=>setLoading(false));},[]);
 const open=invoices.filter(i=>!String(i.status||"").includes("PAID")).reduce((s,i)=>s+Number(i.totalAmount||0),0);const collected=payments.reduce((s,p)=>s+Number(p.amount||0),0);
 const rows=invoices.map(i=>({Account:i.id,Customer:i.customerCode||"—",Invoice:i.billingNumber||i.id,Amount:`${i.currency||"USD"} ${Number(i.totalAmount||0).toFixed(2)}`,Status:i.status||"OPEN",Due:i.billingDate?new Date(i.billingDate).toLocaleDateString():"—"}));
 return <div className="content"><div className="page-head"><div><div className="eyebrow">ORDER TO CASH / RECEIVABLES</div><h1>Accounts Receivable</h1><p>Manage customer open items, incoming payments and receivable closure.</p></div><Link className="btn primary" href="/order-to-cash/accounts-receivable/new-payment">Receive Payment</Link></div>
 <div className="grid stats"><div className="card stat"><div className="stat-label">Open Receivables</div><div className="stat-value">USD {open.toFixed(2)}</div><div className="stat-foot">Live billing balance</div></div><div className="card stat"><div className="stat-label">Open Invoices</div><div className="stat-value">{invoices.filter(i=>!String(i.status||"").includes("PAID")).length}</div><div className="stat-foot">Awaiting settlement</div></div><div className="card stat"><div className="stat-label">Incoming Payments</div><div className="stat-value">{payments.length}</div><div className="stat-foot">Cash receipts</div></div><div className="card stat"><div className="stat-label">Collected</div><div className="stat-value">USD {collected.toFixed(2)}</div><div className="stat-foot success-text">Recorded receipts</div></div></div>
 <section className="card"><div className="table-caption"><strong>Customer Open Items ({rows.length})</strong><span>{loading?"Loading live receivables":"Live backend records"}</span></div><div className="table-wrap"><table className="table"><thead><tr><th>Account</th><th>Customer</th><th>Invoice</th><th>Amount</th><th>Status</th><th>Due</th></tr></thead><tbody>{rows.map(r=><tr key={r.Account}><td>{r.Account}</td><td>{r.Customer}</td><td className="link">{r.Invoice}</td><td>{r.Amount}</td><td>{r.Status}</td><td>{r.Due}</td></tr>)}{!rows.length&&!loading&&<tr><td colSpan={6} className="empty">No receivables found.</td></tr>}</tbody></table></div></section></div>;
}
