"use client";
import {useEffect,useState} from "react";
import {financeApi} from "@/lib/api";

export default function GroupReportingPage(){
 const [companies,setCompanies]=useState<any[]>([]),[groups,setGroups]=useState<any[]>([]),[units,setUnits]=useState<any[]>([]),[runs,setRuns]=useState<any[]>([]),[balances,setBalances]=useState<any[]>([]),[nci,setNci]=useState<any[]>([]),[mappings,setMappings]=useState<any[]>([]),[intercompany,setIntercompany]=useState<any[]>([]),[journals,setJournals]=useState<any[]>([]),[audit,setAudit]=useState<any[]>([]);
 const [groupId,setGroupId]=useState(""),[runId,setRunId]=useState(""),[error,setError]=useState(""),[busy,setBusy]=useState(false);
 const [companyForm,setCompanyForm]=useState({companyCode:"",companyName:"",countryCode:"ZWE",functionalCurrency:"USD",reportingCurrency:"USD"});
 const [unitForm,setUnitForm]=useState({unitCode:"",unitName:"",companyCode:"ZW01",localCurrency:"USD",ownershipPercent:"100"});
 const [groupForm,setGroupForm]=useState({groupCode:"",groupName:"",reportingCurrency:"USD"});
 const [runForm,setRunForm]=useState({fiscalYear:String(new Date().getFullYear()),periodNumber:"1"});
 const [mappingForm,setMappingForm]=useState({groupId:"",companyCode:"ZW01",localAccountCode:"",groupAccountCode:"",groupAccountName:"",groupAccountType:"ASSET"});
 const [icForm,setIcForm]=useState({transactionNumber:"",sourceCompanyCode:"ZW01",targetCompanyCode:"ZW01",transactionDate:new Date().toISOString().slice(0,10),currency:"USD",amount:"",sourceDebitAccountCode:"120000",sourceCreditAccountCode:"400000",targetDebitAccountCode:"500000",targetCreditAccountCode:"210000",description:"Intercompany transaction"});
 const load=async()=>{setBusy(true);try{const [c,g,u]=await Promise.all([financeApi.companyCodes(),financeApi.consolidationGroups(),financeApi.consolidationUnits()]);setCompanies(c);setGroups(g);setUnits(u);setIntercompany(await financeApi.intercompanyTransactions());setError("")}catch(e){setError(e instanceof Error?e.message:"Unable to load group reporting.")}finally{setBusy(false)}};
 useEffect(()=>{load()},[]);
 const loadRuns=async(id:string)=>{setGroupId(id);setRunId("");setBalances([]);if(id){setRuns(await financeApi.groupReportingRuns(id));setMappings(await financeApi.groupAccountMappings(id));setMappingForm(x=>({...x,groupId:id}))}};
 const run=async()=>{if(!groupId)return;setBusy(true);try{const r=await financeApi.runGroupReporting(groupId,{fiscalYear:Number(runForm.fiscalYear),periodNumber:Number(runForm.periodNumber)});setRuns(x=>[r,...x]);setError("")}catch(e){setError(e instanceof Error?e.message:"Unable to run consolidation.")}finally{setBusy(false)}};
 const showBalances=async(id:string)=>{setRunId(id);const [b,n,j,a]=await Promise.all([financeApi.groupReportingBalances(id),financeApi.groupReportingNci(id),financeApi.consolidationJournals(id),financeApi.consolidationRunAudit(id)]);setBalances(b);setNci(n);setJournals(j);setAudit(a)};
 const create=async(kind:"company"|"unit"|"group")=>{setBusy(true);try{if(kind==="company")await financeApi.createCompanyCode(companyForm);if(kind==="unit")await financeApi.saveConsolidationUnit({...unitForm,ownershipPercent:Number(unitForm.ownershipPercent)});if(kind==="group")await financeApi.saveConsolidationGroup(groupForm);await load();setError("")}catch(e){setError(e instanceof Error?e.message:"Save failed")}finally{setBusy(false)}};
 return <main className="content">
  <div className="page-head"><div><div className="eyebrow">FINANCE / GROUP REPORTING</div><h1>Multi-Company & Group Reporting</h1><p>Legal entities, consolidation scope, intercompany postings, currency translation and consolidated balances.</p></div><div className="actions"><button className="btn primary" onClick={load}>{busy?"Working…":"Refresh"}</button></div></div>
  {error&&<div className="alert error">{error}</div>}
  <div className="grid" style={{gridTemplateColumns:"repeat(3,minmax(0,1fr))",marginBottom:18}}>
   <section className="card form-card"><div className="section-title">Company Code</div><div className="form-grid" style={{gridTemplateColumns:"1fr"}}>
    {Object.entries(companyForm).map(([k,v])=><div className="form-field" key={k}><label>{k}</label><input className="form-input" value={v as string} onChange={e=>setCompanyForm({...companyForm,[k]:e.target.value})}/></div>)}<button className="btn primary" onClick={()=>create("company")}>Create Company</button>
   </div></section>
   <section className="card form-card"><div className="section-title">Consolidation Unit</div><div className="form-grid" style={{gridTemplateColumns:"1fr"}}>
    {Object.entries(unitForm).map(([k,v])=><div className="form-field" key={k}><label>{k}</label><input className="form-input" value={v as string} onChange={e=>setUnitForm({...unitForm,[k]:e.target.value})}/></div>)}<button className="btn primary" onClick={()=>create("unit")}>Create Unit</button>
   </div></section>
   <section className="card form-card"><div className="section-title">Consolidation Group</div><div className="form-grid" style={{gridTemplateColumns:"1fr"}}>
    {Object.entries(groupForm).map(([k,v])=><div className="form-field" key={k}><label>{k}</label><input className="form-input" value={v as string} onChange={e=>setGroupForm({...groupForm,[k]:e.target.value})}/></div>)}<button className="btn primary" onClick={()=>create("group")}>Create Group</button>
   </div></section>
  </div>
  <section className="card" style={{marginBottom:18}}><div className="table-caption"><strong>Company Codes</strong><span>{companies.length} active legal entities</span></div><div className="table-wrap"><table className="table"><thead><tr><th>Code</th><th>Name</th><th>Country</th><th>Functional Currency</th><th>Reporting Currency</th></tr></thead><tbody>{companies.map(x=><tr key={x.id}><td>{x.companyCode}</td><td>{x.companyName}</td><td>{x.countryCode}</td><td>{x.functionalCurrency}</td><td>{x.reportingCurrency}</td></tr>)}</tbody></table></div></section>
  <section className="card" style={{marginBottom:18}}><div className="table-caption"><strong>Consolidation Structure</strong><span>{groups.length} groups · {units.length} units</span></div><div className="table-wrap"><table className="table"><thead><tr><th>Group</th><th>Reporting Currency</th><th>Run</th></tr></thead><tbody>{groups.map(g=><tr key={g.id}><td><strong>{g.groupCode}</strong> — {g.groupName}</td><td>{g.reportingCurrency}</td><td><button className="btn" onClick={()=>loadRuns(g.id)}>Select</button></td></tr>)}</tbody></table></div></section>
  <section className="card" style={{marginBottom:18}}><div className="table-caption"><strong>Consolidation Units</strong><span>Add a legal entity to the selected group</span></div><div className="table-wrap"><table className="table"><thead><tr><th>Unit</th><th>Company</th><th>Currency</th><th>Ownership</th><th></th></tr></thead><tbody>{units.map(u=><tr key={u.id}><td>{u.unitCode} — {u.unitName}</td><td>{u.companyCode}</td><td>{u.localCurrency}</td><td>{Number(u.ownershipPercent||0).toFixed(2)}%</td><td><button className="btn" disabled={!groupId} onClick={async()=>{try{await financeApi.addConsolidationUnit(groupId,u.id);await loadRuns(groupId);setError("")}catch(e){setError(e instanceof Error?e.message:"Unable to add unit.")}}}>Add to selected group</button></td></tr>)}</tbody></table></div></section>
  <section className="card" style={{marginBottom:18}}><div className="section-title">Intercompany Transaction</div><p className="muted">Post balanced source and target company entries with explicit elimination accounts.</p><div className="form-grid">{Object.entries(icForm).map(([k,v])=><div className="form-field" key={k}><label>{k}</label><input className="form-input" type={k==="amount"?"number":k==="transactionDate"?"date":"text"} value={v as string} onChange={e=>setIcForm({...icForm,[k]:e.target.value})}/></div>)}<div className="form-field"><label>&nbsp;</label><button className="btn primary" onClick={async()=>{try{await financeApi.postIntercompany({...icForm,amount:Number(icForm.amount)});setIntercompany(await financeApi.intercompanyTransactions());setError("")}catch(e){setError(e instanceof Error?e.message:"Unable to post intercompany transaction.")}}>Post Intercompany</button></div></div><div className="table-wrap"><table className="table"><thead><tr><th>Transaction</th><th>Date</th><th>Source</th><th>Target</th><th>Amount</th><th>Currency</th><th>Status</th></tr></thead><tbody>{intercompany.map(x=><tr key={x.id}><td>{x.transactionNumber}</td><td>{x.transactionDate}</td><td>{x.sourceCompanyCode}</td><td>{x.targetCompanyCode}</td><td>{Number(x.amount||0).toFixed(2)}</td><td>{x.currency}</td><td>{x.status}</td></tr>)}</tbody></table></div></section>
  {groupId&&<section className="card" style={{marginBottom:18}}><div className="section-title">Group Chart of Accounts Mapping</div><p className="muted">Map local company accounts to a common group reporting account before consolidation.</p><div className="form-grid"><div className="form-field"><label>Company</label><select className="form-input" value={mappingForm.companyCode} onChange={e=>setMappingForm({...mappingForm,companyCode:e.target.value})}>{companies.map(x=><option key={x.id}>{x.companyCode}</option>)}</select></div><div className="form-field"><label>Local Account</label><input className="form-input" value={mappingForm.localAccountCode} onChange={e=>setMappingForm({...mappingForm,localAccountCode:e.target.value})}/></div><div className="form-field"><label>Group Account</label><input className="form-input" value={mappingForm.groupAccountCode} onChange={e=>setMappingForm({...mappingForm,groupAccountCode:e.target.value})}/></div><div className="form-field"><label>Group Name</label><input className="form-input" value={mappingForm.groupAccountName} onChange={e=>setMappingForm({...mappingForm,groupAccountName:e.target.value})}/></div><div className="form-field"><label>Group Type</label><select className="form-input" value={mappingForm.groupAccountType} onChange={e=>setMappingForm({...mappingForm,groupAccountType:e.target.value})}>{["ASSET","LIABILITY","EQUITY","REVENUE","EXPENSE","OTHER"].map(x=><option key={x}>{x}</option>)}</select></div><div className="form-field"><label>&nbsp;</label><button className="btn primary" onClick={async()=>{try{await financeApi.createGroupAccountMapping(mappingForm);setMappings(await financeApi.groupAccountMappings(groupId));setError("")}catch(e){setError(e instanceof Error?e.message:"Unable to save account mapping.")}}>Add Mapping</button></div></div><div className="table-wrap"><table className="table"><thead><tr><th>Company</th><th>Local</th><th>Group</th><th>Name</th><th>Type</th></tr></thead><tbody>{mappings.map(x=><tr key={x.id}><td>{x.companyCode}</td><td>{x.localAccountCode}</td><td>{x.groupAccountCode}</td><td>{x.groupAccountName}</td><td>{x.groupAccountType}</td></tr>)}</tbody></table></div></section>}
  {groupId&&<section className="card" style={{marginBottom:18}}><div className="section-title">Run Consolidation</div><div className="form-grid"><div className="form-field"><label>Fiscal Year</label><input className="form-input" value={runForm.fiscalYear} onChange={e=>setRunForm({...runForm,fiscalYear:e.target.value})}/></div><div className="form-field"><label>Period</label><select className="form-input" value={runForm.periodNumber} onChange={e=>setRunForm({...runForm,periodNumber:e.target.value})}>{Array.from({length:12},(_,i)=><option key={i+1}>{i+1}</option>)}</select></div><div className="form-field"><label>&nbsp;</label><button className="btn primary" onClick={run} disabled={busy}>Run Group Reporting</button></div></div>
   <div className="table-wrap"><table className="table"><thead><tr><th>Year</th><th>Period</th><th>Currency</th><th>Status</th><th>Debit</th><th>Credit</th><th>NCI</th><th></th></tr></thead><tbody>{runs.map(x=><tr key={x.id}><td>{x.fiscalYear}</td><td>{x.periodNumber}</td><td>{x.reportingCurrency}</td><td>{x.status}</td><td>{Number(x.totalDebit||0).toFixed(2)}</td><td>{Number(x.totalCredit||0).toFixed(2)}</td><td>{Number(x.nciAmount||0).toFixed(2)}</td><td><button className="btn" onClick={()=>showBalances(x.id)}>View balances</button></td></tr>)}</tbody></table></div>
  </section>}
  {runId&&<><section className="card" style={{marginBottom:18}}><div className="table-caption"><strong>Consolidation Journals</strong><span>{journals.length} journals</span></div><div className="table-wrap"><table className="table"><thead><tr><th>Journal</th><th>Type</th><th>Date</th><th>Status</th><th>Debit</th><th>Credit</th></tr></thead><tbody>{journals.map(x=><tr key={x.id}><td>{x.journalNumber}</td><td>{x.journalType}</td><td>{x.postingDate}</td><td>{x.status}</td><td>{Number(x.totalDebit||0).toFixed(2)}</td><td>{Number(x.totalCredit||0).toFixed(2)}</td></tr>)}</tbody></table></div></section><section className="card" style={{marginBottom:18}}><div className="table-caption"><strong>Consolidation Audit Trail</strong><span>{audit.length} events</span></div><div className="table-wrap"><table className="table"><thead><tr><th>Time</th><th>Event</th><th>Status</th><th>Actor</th><th>Reference</th><th>Details</th></tr></thead><tbody>{audit.map(x=><tr key={x.id}><td>{x.eventTime}</td><td>{x.eventType}</td><td>{x.eventStatus}</td><td>{x.actor}</td><td>{x.referenceNumber||"—"}</td><td>{x.details}</td></tr>)}</tbody></table></div></section><section className="card" style={{marginBottom:18}}><div className="table-caption"><strong>Non-Controlling Interest</strong><span>{nci.length} minority interests</span></div><span>{nci.length} minority interests</span></div><div className="table-wrap"><table className="table"><thead><tr><th>Entity</th><th>Ownership</th><th>NCI %</th><th>Net Assets</th><th>NCI Amount</th></tr></thead><tbody>{nci.map(x=><tr key={x.id}><td>{x.unit?.unitCode||"—"} — {x.unit?.unitName||x.unit?.companyCode||"—"}</td><td>{Number(x.ownershipPercent||0).toFixed(2)}%</td><td>{Number(x.nciPercent||0).toFixed(2)}%</td><td>{Number(x.netAssets||0).toFixed(2)}</td><td><strong>{Number(x.nciAmount||0).toFixed(2)}</strong></td></tr>)}</tbody></table></div></section></section>}
  {runId&&<section className="card"><div className="table-caption"><strong>Consolidated Trial Balance</strong><span>Eliminations included</span></div><div className="table-wrap"><table className="table"><thead><tr><th>Company</th><th>Account</th><th>Type</th><th>FX</th><th>Translated Debit</th><th>Translated Credit</th><th>Elim Debit</th><th>Elim Credit</th><th>Final Debit</th><th>Final Credit</th></tr></thead><tbody>{balances.map(x=><tr key={x.id}><td>{x.companyCode}</td><td>{x.accountCode} — {x.accountName}</td><td>{x.accountType}</td><td>{Number(x.fxRate||1).toFixed(6)}</td><td>{Number(x.translatedDebit||0).toFixed(2)}</td><td>{Number(x.translatedCredit||0).toFixed(2)}</td><td>{Number(x.eliminationDebit||0).toFixed(2)}</td><td>{Number(x.eliminationCredit||0).toFixed(2)}</td><td>{Number(x.finalDebit||0).toFixed(2)}</td><td>{Number(x.finalCredit||0).toFixed(2)}</td></tr>)}</tbody></table></div></section>}
 </main>
}