CREATE TABLE IF NOT EXISTS cost_centers (
 id UUID PRIMARY KEY,
 code VARCHAR(30) NOT NULL UNIQUE,
 name VARCHAR(150) NOT NULL,
 responsible_person VARCHAR(150),
 active BOOLEAN NOT NULL DEFAULT TRUE,
 created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 version BIGINT NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS bank_accounts (
 id UUID PRIMARY KEY,
 account_number VARCHAR(60) NOT NULL UNIQUE,
 bank_name VARCHAR(150) NOT NULL,
 branch_name VARCHAR(150),
 currency VARCHAR(3) NOT NULL,
 gl_account_code VARCHAR(20) NOT NULL,
 active BOOLEAN NOT NULL DEFAULT TRUE,
 created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 version BIGINT NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS fixed_assets (
 id UUID PRIMARY KEY,
 asset_number VARCHAR(40) NOT NULL UNIQUE,
 asset_name VARCHAR(200) NOT NULL,
 asset_class VARCHAR(80) NOT NULL,
 acquisition_date DATE NOT NULL,
 acquisition_cost NUMERIC(19,2) NOT NULL,
 useful_life_months INTEGER NOT NULL,
 accumulated_depreciation NUMERIC(19,2) NOT NULL DEFAULT 0,
 residual_value NUMERIC(19,2) NOT NULL DEFAULT 0,
 cost_center_code VARCHAR(30),
 status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
 active BOOLEAN NOT NULL DEFAULT TRUE,
 created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 version BIGINT NOT NULL DEFAULT 0
);

CREATE INDEX IF NOT EXISTS idx_fixed_assets_cost_center ON fixed_assets(cost_center_code);
CREATE INDEX IF NOT EXISTS idx_fixed_assets_status ON fixed_assets(status);
