CREATE TABLE IF NOT EXISTS credit_profiles (
 id UUID PRIMARY KEY, customer_id UUID NOT NULL UNIQUE, credit_limit NUMERIC(19,2) NOT NULL DEFAULT 0,
 credit_score INTEGER, risk_class VARCHAR(30), blocked BOOLEAN NOT NULL DEFAULT FALSE,
 review_date DATE, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 active BOOLEAN NOT NULL DEFAULT TRUE, version BIGINT NOT NULL DEFAULT 0,
 CONSTRAINT chk_credit_limit CHECK (credit_limit >= 0), CONSTRAINT chk_credit_score CHECK (credit_score IS NULL OR (credit_score BETWEEN 0 AND 1000))
);
CREATE TABLE IF NOT EXISTS collection_cases (
 id UUID PRIMARY KEY, customer_id UUID NOT NULL, invoice_reference VARCHAR(100) NOT NULL,
 due_date DATE, amount_due NUMERIC(19,2) NOT NULL, status VARCHAR(30) NOT NULL DEFAULT 'OPEN',
 priority VARCHAR(20) NOT NULL DEFAULT 'NORMAL', assigned_to VARCHAR(150), promise_date DATE,
 promise_amount NUMERIC(19,2), notes VARCHAR(1000), created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, active BOOLEAN NOT NULL DEFAULT TRUE, version BIGINT NOT NULL DEFAULT 0,
 CONSTRAINT chk_collection_amount CHECK (amount_due >= 0)
);
CREATE INDEX IF NOT EXISTS idx_collection_customer_status ON collection_cases(customer_id,status);
CREATE TABLE IF NOT EXISTS finance_disputes (
 id UUID PRIMARY KEY, customer_id UUID NOT NULL, invoice_reference VARCHAR(100) NOT NULL,
 reason_code VARCHAR(50) NOT NULL, amount NUMERIC(19,2) NOT NULL, status VARCHAR(30) NOT NULL DEFAULT 'OPEN',
 owner VARCHAR(150), resolution VARCHAR(1000), resolved_at TIMESTAMP, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, active BOOLEAN NOT NULL DEFAULT TRUE, version BIGINT NOT NULL DEFAULT 0
);
CREATE TABLE IF NOT EXISTS revenue_contracts (
 id UUID PRIMARY KEY, contract_number VARCHAR(80) NOT NULL UNIQUE, customer_id UUID NOT NULL, contract_date DATE NOT NULL,
 currency VARCHAR(3) NOT NULL, transaction_price NUMERIC(19,2) NOT NULL, status VARCHAR(20) NOT NULL DEFAULT 'OPEN',
 created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, active BOOLEAN NOT NULL DEFAULT TRUE, version BIGINT NOT NULL DEFAULT 0
);
CREATE TABLE IF NOT EXISTS revenue_obligations (
 id UUID PRIMARY KEY, contract_id UUID NOT NULL REFERENCES revenue_contracts(id), obligation_code VARCHAR(50) NOT NULL,
 description VARCHAR(250) NOT NULL, standalone_price NUMERIC(19,2) NOT NULL, allocated_price NUMERIC(19,2) NOT NULL DEFAULT 0,
 fulfilled_amount NUMERIC(19,2) NOT NULL DEFAULT 0, status VARCHAR(20) NOT NULL DEFAULT 'OPEN',
 created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 active BOOLEAN NOT NULL DEFAULT TRUE, version BIGINT NOT NULL DEFAULT 0,
 CONSTRAINT uq_revenue_obligation UNIQUE(contract_id,obligation_code)
);
CREATE TABLE IF NOT EXISTS revenue_recognition_events (
 id UUID PRIMARY KEY, obligation_id UUID NOT NULL REFERENCES revenue_obligations(id), event_date DATE NOT NULL,
 amount NUMERIC(19,2) NOT NULL, recognition_type VARCHAR(30) NOT NULL, accounting_document_id UUID,
 created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, UNIQUE(obligation_id,event_date,recognition_type)
);
CREATE TABLE IF NOT EXISTS consolidation_units (
 id UUID PRIMARY KEY, unit_code VARCHAR(30) NOT NULL UNIQUE, unit_name VARCHAR(150) NOT NULL, local_currency VARCHAR(3) NOT NULL,
 ownership_percent NUMERIC(7,4) NOT NULL DEFAULT 100, active BOOLEAN NOT NULL DEFAULT TRUE, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, version BIGINT NOT NULL DEFAULT 0
);
CREATE TABLE IF NOT EXISTS consolidation_groups (
 id UUID PRIMARY KEY, group_code VARCHAR(30) NOT NULL UNIQUE, group_name VARCHAR(150) NOT NULL, reporting_currency VARCHAR(3) NOT NULL,
 active BOOLEAN NOT NULL DEFAULT TRUE, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, version BIGINT NOT NULL DEFAULT 0
);
CREATE TABLE IF NOT EXISTS consolidation_group_units (
 group_id UUID NOT NULL REFERENCES consolidation_groups(id), unit_id UUID NOT NULL REFERENCES consolidation_units(id),
 PRIMARY KEY(group_id,unit_id)
);
CREATE TABLE IF NOT EXISTS consolidation_adjustments (
 id UUID PRIMARY KEY, group_id UUID NOT NULL REFERENCES consolidation_groups(id), unit_code VARCHAR(30),
 account_code VARCHAR(20) NOT NULL, debit NUMERIC(19,2) NOT NULL DEFAULT 0, credit NUMERIC(19,2) NOT NULL DEFAULT 0,
 reason VARCHAR(500) NOT NULL, period_start DATE NOT NULL, status VARCHAR(20) NOT NULL DEFAULT 'POSTED',
 created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, version BIGINT NOT NULL DEFAULT 0
);
CREATE TABLE IF NOT EXISTS funds (
 id UUID PRIMARY KEY, fund_code VARCHAR(40) NOT NULL UNIQUE, fund_name VARCHAR(150) NOT NULL, currency VARCHAR(3) NOT NULL,
 budget_amount NUMERIC(19,2) NOT NULL DEFAULT 0, active BOOLEAN NOT NULL DEFAULT TRUE, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, version BIGINT NOT NULL DEFAULT 0
);
CREATE TABLE IF NOT EXISTS fund_commitments (
 id UUID PRIMARY KEY, fund_id UUID NOT NULL REFERENCES funds(id), commitment_item VARCHAR(50) NOT NULL, funds_center VARCHAR(50) NOT NULL,
 functional_area VARCHAR(50), reference_number VARCHAR(100) NOT NULL, committed_amount NUMERIC(19,2) NOT NULL,
 actual_amount NUMERIC(19,2) NOT NULL DEFAULT 0, status VARCHAR(20) NOT NULL DEFAULT 'OPEN', created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 version BIGINT NOT NULL DEFAULT 0
);
CREATE TABLE IF NOT EXISTS tax_codes (
 id UUID PRIMARY KEY, tax_code VARCHAR(20) NOT NULL UNIQUE, description VARCHAR(150) NOT NULL, rate NUMERIC(9,4) NOT NULL,
 input_account_code VARCHAR(20), output_account_code VARCHAR(20), withholding BOOLEAN NOT NULL DEFAULT FALSE, active BOOLEAN NOT NULL DEFAULT TRUE,
 created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, version BIGINT NOT NULL DEFAULT 0,
 CONSTRAINT chk_tax_rate CHECK (rate >= 0 AND rate <= 100)
);
CREATE TABLE IF NOT EXISTS fx_rates (
 id UUID PRIMARY KEY, rate_date DATE NOT NULL, from_currency VARCHAR(3) NOT NULL, to_currency VARCHAR(3) NOT NULL, rate NUMERIC(19,8) NOT NULL,
 source VARCHAR(50) NOT NULL DEFAULT 'MANUAL', created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 UNIQUE(rate_date,from_currency,to_currency), CONSTRAINT chk_fx_rate CHECK (rate > 0)
);
CREATE TABLE IF NOT EXISTS accrual_templates (
 id UUID PRIMARY KEY, template_code VARCHAR(50) NOT NULL UNIQUE, description VARCHAR(250) NOT NULL,
 expense_account_code VARCHAR(20) NOT NULL, liability_account_code VARCHAR(20) NOT NULL, amount NUMERIC(19,2) NOT NULL,
 cost_center_code VARCHAR(30), frequency VARCHAR(20) NOT NULL DEFAULT 'MONTHLY', next_run_date DATE NOT NULL,
 active BOOLEAN NOT NULL DEFAULT TRUE, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, version BIGINT NOT NULL DEFAULT 0
);
CREATE TABLE IF NOT EXISTS accrual_runs (
 id UUID PRIMARY KEY, template_id UUID NOT NULL REFERENCES accrual_templates(id), period_start DATE NOT NULL,
 amount NUMERIC(19,2) NOT NULL, accounting_document_id UUID NOT NULL, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 UNIQUE(template_id,period_start)
);
CREATE TABLE IF NOT EXISTS product_cost_estimates (
 id UUID PRIMARY KEY, product_code VARCHAR(80) NOT NULL, costing_date DATE NOT NULL, standard_cost NUMERIC(19,2) NOT NULL,
 material_cost NUMERIC(19,2) NOT NULL DEFAULT 0, labor_cost NUMERIC(19,2) NOT NULL DEFAULT 0, overhead_cost NUMERIC(19,2) NOT NULL DEFAULT 0,
 status VARCHAR(20) NOT NULL DEFAULT 'CREATED', released_at TIMESTAMP, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 UNIQUE(product_code,costing_date), CONSTRAINT chk_standard_cost CHECK (standard_cost >= 0)
);
CREATE TABLE IF NOT EXISTS material_ledger_periods (
 id UUID PRIMARY KEY, product_code VARCHAR(80) NOT NULL, period_start DATE NOT NULL, quantity NUMERIC(19,6) NOT NULL DEFAULT 0,
 standard_value NUMERIC(19,2) NOT NULL DEFAULT 0, actual_value NUMERIC(19,2) NOT NULL DEFAULT 0, actual_unit_cost NUMERIC(19,6) NOT NULL DEFAULT 0,
 status VARCHAR(20) NOT NULL DEFAULT 'OPEN', UNIQUE(product_code,period_start)
);
