CREATE TABLE IF NOT EXISTS treasury_instruments (
 id UUID PRIMARY KEY, instrument_number VARCHAR(80) NOT NULL UNIQUE, instrument_type VARCHAR(30) NOT NULL,
 counterparty VARCHAR(150) NOT NULL, currency VARCHAR(3) NOT NULL, notional_amount NUMERIC(19,2) NOT NULL,
 trade_date DATE NOT NULL, maturity_date DATE, status VARCHAR(20) NOT NULL DEFAULT 'OPEN',
 valuation_amount NUMERIC(19,2) NOT NULL DEFAULT 0, hedge_designated BOOLEAN NOT NULL DEFAULT FALSE,
 created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 active BOOLEAN NOT NULL DEFAULT TRUE, version BIGINT NOT NULL DEFAULT 0
);
CREATE TABLE IF NOT EXISTS treasury_risk_limits (
 id UUID PRIMARY KEY, limit_code VARCHAR(50) NOT NULL UNIQUE, counterparty VARCHAR(150), currency VARCHAR(3),
 instrument_type VARCHAR(30), limit_amount NUMERIC(19,2) NOT NULL, active BOOLEAN NOT NULL DEFAULT TRUE,
 created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, version BIGINT NOT NULL DEFAULT 0
);