-- Quality Management
CREATE TABLE IF NOT EXISTS qm_master_inspection_characteristics (
 id UUID PRIMARY KEY, code VARCHAR(50) NOT NULL UNIQUE, name VARCHAR(150) NOT NULL,
 data_type VARCHAR(30) NOT NULL, lower_tolerance NUMERIC(19,6), upper_tolerance NUMERIC(19,6),
 unit_of_measure VARCHAR(30), created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, active BOOLEAN DEFAULT TRUE, version BIGINT DEFAULT 0
);
CREATE TABLE IF NOT EXISTS qm_inspection_plans (
 id UUID PRIMARY KEY, plan_number VARCHAR(50) NOT NULL UNIQUE, product_id UUID NOT NULL REFERENCES products(id),
 plant_code VARCHAR(30) NOT NULL, version VARCHAR(30), status VARCHAR(20) NOT NULL,
 created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 active BOOLEAN DEFAULT TRUE, version_no BIGINT DEFAULT 0
);
CREATE TABLE IF NOT EXISTS qm_inspection_plan_chars (
 id UUID PRIMARY KEY, plan_id UUID NOT NULL REFERENCES qm_inspection_plans(id) ON DELETE CASCADE,
 characteristic_id UUID NOT NULL REFERENCES qm_master_inspection_characteristics(id),
 sample_size INTEGER NOT NULL, sequence_no INTEGER NOT NULL,
 created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 active BOOLEAN DEFAULT TRUE, version BIGINT DEFAULT 0
);
CREATE TABLE IF NOT EXISTS qm_quality_info_records (
 id UUID PRIMARY KEY, supplier_id UUID NOT NULL REFERENCES suppliers(id), product_id UUID NOT NULL REFERENCES products(id),
 inspection_required BOOLEAN NOT NULL, skip_lot_after_good_lots INTEGER,
 created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 active BOOLEAN DEFAULT TRUE, version BIGINT DEFAULT 0, UNIQUE(supplier_id,product_id)
);
CREATE TABLE IF NOT EXISTS qm_inspection_lots (
 id UUID PRIMARY KEY, lot_number VARCHAR(50) NOT NULL UNIQUE, inspection_type VARCHAR(20) NOT NULL,
 product_id UUID NOT NULL REFERENCES products(id), plant_code VARCHAR(30) NOT NULL,
 source_document_type VARCHAR(50), source_document_id UUID, quantity NUMERIC(19,6) NOT NULL,
 status VARCHAR(30) NOT NULL, created_on TIMESTAMP NOT NULL,
 created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 active BOOLEAN DEFAULT TRUE, version BIGINT DEFAULT 0
);
CREATE TABLE IF NOT EXISTS qm_inspection_results (
 id UUID PRIMARY KEY, inspection_lot_id UUID NOT NULL REFERENCES qm_inspection_lots(id) ON DELETE CASCADE,
 characteristic_id UUID NOT NULL REFERENCES qm_master_inspection_characteristics(id),
 measured_value NUMERIC(19,6), qualitative_result VARCHAR(100), result_status VARCHAR(20) NOT NULL,
 defect_type VARCHAR(100), defect_cause VARCHAR(100),
 created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 active BOOLEAN DEFAULT TRUE, version BIGINT DEFAULT 0
);
CREATE TABLE IF NOT EXISTS qm_usage_decisions (
 id UUID PRIMARY KEY, inspection_lot_id UUID NOT NULL UNIQUE REFERENCES qm_inspection_lots(id),
 decision_code VARCHAR(30) NOT NULL, stock_action VARCHAR(30) NOT NULL, remarks VARCHAR(1000),
 created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 active BOOLEAN DEFAULT TRUE, version BIGINT DEFAULT 0
);
CREATE TABLE IF NOT EXISTS qm_notifications (
 id UUID PRIMARY KEY, notification_number VARCHAR(50) NOT NULL UNIQUE, notification_type VARCHAR(20) NOT NULL,
 priority VARCHAR(20) NOT NULL, short_text VARCHAR(255) NOT NULL, status VARCHAR(30) NOT NULL,
 reference_object_type VARCHAR(50), reference_object_id UUID,
 created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 active BOOLEAN DEFAULT TRUE, version BIGINT DEFAULT 0
);
CREATE TABLE IF NOT EXISTS qm_notification_items (
 id UUID PRIMARY KEY, notification_id UUID NOT NULL REFERENCES qm_notifications(id) ON DELETE CASCADE,
 defect_type VARCHAR(100) NOT NULL, object_part VARCHAR(100), cause VARCHAR(100), description VARCHAR(1000),
 created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 active BOOLEAN DEFAULT TRUE, version BIGINT DEFAULT 0
);
CREATE TABLE IF NOT EXISTS qm_notification_tasks (
 id UUID PRIMARY KEY, notification_id UUID NOT NULL REFERENCES qm_notifications(id) ON DELETE CASCADE,
 task VARCHAR(255) NOT NULL, owner VARCHAR(100), status VARCHAR(30) NOT NULL, completion_notes VARCHAR(1000),
 created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 active BOOLEAN DEFAULT TRUE, version BIGINT DEFAULT 0
);

-- Manufacturing
CREATE TABLE IF NOT EXISTS mfg_boms (
 id UUID PRIMARY KEY, bom_number VARCHAR(50) NOT NULL UNIQUE, product_id UUID NOT NULL REFERENCES products(id),
 plant_code VARCHAR(30) NOT NULL, version VARCHAR(30), status VARCHAR(20) NOT NULL,
 created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 active BOOLEAN DEFAULT TRUE, version_no BIGINT DEFAULT 0
);
CREATE TABLE IF NOT EXISTS mfg_bom_items (
 id UUID PRIMARY KEY, bom_id UUID NOT NULL REFERENCES mfg_boms(id) ON DELETE CASCADE,
 component_product_id UUID NOT NULL REFERENCES products(id), quantity NUMERIC(19,6) NOT NULL,
 uom VARCHAR(30), sequence_no INTEGER NOT NULL,
 created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 active BOOLEAN DEFAULT TRUE, version BIGINT DEFAULT 0
);
CREATE TABLE IF NOT EXISTS mfg_routings (
 id UUID PRIMARY KEY, routing_number VARCHAR(50) NOT NULL UNIQUE, product_id UUID NOT NULL REFERENCES products(id),
 plant_code VARCHAR(30) NOT NULL, version VARCHAR(30), status VARCHAR(20) NOT NULL,
 created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 active BOOLEAN DEFAULT TRUE, version_no BIGINT DEFAULT 0
);
CREATE TABLE IF NOT EXISTS mfg_routing_operations (
 id UUID PRIMARY KEY, routing_id UUID NOT NULL REFERENCES mfg_routings(id) ON DELETE CASCADE,
 operation_no INTEGER NOT NULL, description VARCHAR(255) NOT NULL, work_center VARCHAR(100),
 setup_minutes NUMERIC(19,6), run_minutes NUMERIC(19,6),
 created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 active BOOLEAN DEFAULT TRUE, version BIGINT DEFAULT 0
);
CREATE TABLE IF NOT EXISTS mfg_production_orders (
 id UUID PRIMARY KEY, order_number VARCHAR(50) NOT NULL UNIQUE, product_id UUID NOT NULL REFERENCES products(id),
 bom_id UUID REFERENCES mfg_boms(id), routing_id UUID REFERENCES mfg_routings(id), plant_code VARCHAR(30) NOT NULL,
 planned_quantity NUMERIC(19,6) NOT NULL, confirmed_quantity NUMERIC(19,6) NOT NULL DEFAULT 0,
 order_type VARCHAR(30) NOT NULL, status VARCHAR(30) NOT NULL, planned_start_date DATE, planned_finish_date DATE,
 created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 active BOOLEAN DEFAULT TRUE, version BIGINT DEFAULT 0
);
CREATE TABLE IF NOT EXISTS mfg_production_order_materials (
 id UUID PRIMARY KEY, production_order_id UUID NOT NULL REFERENCES mfg_production_orders(id) ON DELETE CASCADE,
 component_product_id UUID NOT NULL REFERENCES products(id), required_quantity NUMERIC(19,6) NOT NULL,
 issued_quantity NUMERIC(19,6) NOT NULL DEFAULT 0,
 created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 active BOOLEAN DEFAULT TRUE, version BIGINT DEFAULT 0
);
CREATE TABLE IF NOT EXISTS mfg_production_confirmations (
 id UUID PRIMARY KEY, production_order_id UUID NOT NULL REFERENCES mfg_production_orders(id),
 quantity NUMERIC(19,6) NOT NULL, scrap_quantity NUMERIC(19,6) NOT NULL DEFAULT 0,
 confirmation_time TIMESTAMP NOT NULL, operation VARCHAR(100), remarks VARCHAR(1000),
 created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 active BOOLEAN DEFAULT TRUE, version BIGINT DEFAULT 0
);
CREATE TABLE IF NOT EXISTS mfg_capacity_records (
 id UUID PRIMARY KEY, work_center VARCHAR(100) NOT NULL, capacity_date DATE NOT NULL,
 available_minutes NUMERIC(19,6) NOT NULL, planned_minutes NUMERIC(19,6) NOT NULL,
 created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 active BOOLEAN DEFAULT TRUE, version BIGINT DEFAULT 0, UNIQUE(work_center,capacity_date)
);
CREATE TABLE IF NOT EXISTS mfg_kanban_control_cycles (
 id UUID PRIMARY KEY, cycle_code VARCHAR(50) NOT NULL UNIQUE, product_id UUID NOT NULL REFERENCES products(id),
 plant_code VARCHAR(30) NOT NULL, containers INTEGER NOT NULL, container_quantity NUMERIC(19,6) NOT NULL,
 replenishment_strategy VARCHAR(30) NOT NULL,
 created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 active BOOLEAN DEFAULT TRUE, version BIGINT DEFAULT 0
);
CREATE TABLE IF NOT EXISTS mfg_kanban_signals (
 id UUID PRIMARY KEY, control_cycle_id UUID NOT NULL REFERENCES mfg_kanban_control_cycles(id),
 status VARCHAR(40) NOT NULL, trigger_source VARCHAR(100),
 created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 active BOOLEAN DEFAULT TRUE, version BIGINT DEFAULT 0
);
CREATE TABLE IF NOT EXISTS mfg_mrp_plans (
 id UUID PRIMARY KEY, plant_code VARCHAR(30) NOT NULL, strategy_group VARCHAR(30),
 run_time TIMESTAMP NOT NULL, status VARCHAR(30) NOT NULL, demand_count INTEGER NOT NULL, planned_order_count INTEGER NOT NULL,
 created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 active BOOLEAN DEFAULT TRUE, version BIGINT DEFAULT 0
);
