"use client";

import Link from "next/link";
import {useEffect,useState} from "react";
import {ModuleWorkspace} from "@/components/ModuleWorkspace";
import {orderToCashApi} from "@/lib/api";

export default function OrderToCash(){
 const [data,setData]=useState({orders:[] as any[],deliveries:[] as any[],invoices:[] as any[],payments:[] as any[]});const [loading,setLoading]=useState(true);
 useEffect(()=>{Promise.all([orderToCashApi.salesOrders(),orderToCashApi.deliveries(),orderToCashApi.billingDocuments(),orderToCashApi.incomingPayments()]).then(([orders,deliveries,invoices,payments])=>setData({orders,deliveries,invoices,payments})).catch(()=>{}).finally(()=>setLoading(false));},[]);
 const rows=data.orders.slice(0,10).map(o=>({Document:o.orderNumber||o.sapOrderNumber||o.id,Customer:o.customerCode||"—",Value:`USD ${Number(o.totalAmount||0).toFixed(2)}`,Status:o.status||"DRAFT",Next:data.deliveries.some(d=>d.salesOrderId===o.id)?"Delivery":"Fulfilment"}));
 const openOrders=data.orders.filter(o=>!String(o.status||"").includes("CANCEL")).length;const openDeliveries=data.deliveries.filter(d=>!String(d.status||"").includes("GOODS_ISSUE")&&!String(d.status||"").includes("DELIVERED")).length;const openInvoices=data.invoices.filter(i=>!String(i.status||"").includes("PAID")).length;const receivable=data.invoices.filter(i=>!String(i.status||"").includes("PAID")).reduce((s,i)=>s+Number(i.totalAmount||0),0)-data.payments.reduce((s,p)=>s+Number(p.amount||0),0);
 return <ModuleWorkspace eyebrow="ORDER TO CASH / OVERVIEW" title="Order to Cash" description="Manage the customer cycle from sales order through delivery, billing, receivables and incoming payment." createHref="/order-to-cash/sales-orders/new" createLabel="Create Sales Order" stats={[{label:"Open Sales Orders",value:String(openOrders),foot:loading?"Loading live orders":"Live backend records"},{label:"Open Deliveries",value:String(openDeliveries),foot:"Picking / packing / PGI",tone:"warning"},{label:"Open Customer Invoices",value:String(openInvoices),foot:"Awaiting settlement"},{label:"Receivables",value:`USD ${Math.max(receivable,0).toFixed(2)}`,foot:"Invoice balance less receipts",tone:"warning"}]} process={[{label:"Sales Order",detail:"Create customer order",status:loading?"Loading":"Live",tone:"ready"},{label:"Delivery",detail:"Pick, pack & PGI",status:String(openDeliveries),tone:"pending"},{label:"Customer Invoice",detail:"Billing document",status:String(data.invoices.length),tone:"ready"},{label:"Incoming Payment",detail:"Cash receipt",status:String(data.payments.length),tone:"pending"},{label:"Closure",detail:"Clear receivable",status:openInvoices?"Open":"Complete",tone:openInvoices?"draft":"approved"}]} columns={["Document","Customer","Value","Status","Next"]} rows={rows} searchPlaceholder="Search sales order or customer...">
 <div className="grid dashboard-grid" style={{marginBottom:18}}><section className="card"><div className="section-title">Order to Cash Modules</div>{[["Sales Orders","/order-to-cash/sales-orders","Order entry and pricing"],["Deliveries","/order-to-cash/deliveries","Picking, packing and PGI"],["Customer Invoices","/order-to-cash/customer-invoices","Billing and posting"],["Accounts Receivable","/order-to-cash/accounts-receivable","Open items and collections"]].map(([label,href,detail])=><div className="list-row" key={href}><div><Link className="link" href={href}>{label}</Link><div className="muted">{detail}</div></div><span className="chevron">›</span></div>)}</section><section className="card"><div className="section-title">Document Flow</div><div className="detail-grid"><div className="detail-field"><span>Commercial</span><strong>Sales Order → Delivery → Invoice</strong></div><div className="detail-field"><span>Financial</span><strong>Invoice → Receivable → Payment</strong></div><div className="detail-field"><span>Closure</span><strong>Incoming payment allocation and clearing</strong></div></div></section></div>
 </ModuleWorkspace>;
}
