"use client";
import Link from "next/link";
import {useEffect,useState} from "react";
import {orderToCashApi} from "@/lib/api";

export default function ReceivePayment(){
 const [form,setForm]=useState({billingDocumentId:"",amount:"",currency:"USD",reference:""}); const [billing,setBilling]=useState<any[]>([]);const [saving,setSaving]=useState(false);const [message,setMessage]=useState(""); useEffect(()=>{orderToCashApi.billingDocuments().then(r=>setBilling(r.filter((x:any)=>x.status==="POSTED"))).catch(()=>setBilling([]));},[]);const set=(k:keyof typeof form,v:string)=>setForm(x=>({...x,[k]:v}));
 const submit=async()=>{setSaving(true);setMessage("");try{const r=await orderToCashApi.receiveIncomingPayment({billingDocumentId:form.billingDocumentId,amount:Number(form.amount),currency:form.currency,reference:form.reference});setMessage(`Incoming payment ${r.paymentNumber||""} recorded.`);}catch(e){setMessage(e instanceof Error?e.message:"Unable to record payment.");}finally{setSaving(false);}};
 return <div className="content"><div className="document-head"><div><div className="eyebrow">ORDER TO CASH / RECEIVABLES</div><h1>Receive Customer Payment</h1><p>Record an incoming receipt against a customer billing document.</p></div><div className="actions"><Link className="btn" href="/order-to-cash/accounts-receivable">Cancel</Link><button className="btn primary" disabled={saving||!form.billingDocumentId||!form.amount} onClick={submit}>{saving?"Recording…":"Record Payment"}</button></div></div>{message&&<div className="alert">{message}</div>}<section className="card form-card"><div className="section-title">Receipt Details</div><div className="form-grid"><div className="form-field"><label>Billing Document *</label><select className="form-input" value={form.billingDocumentId} onChange={e=>{const id=e.target.value;const b=billing.find(x=>x.id===id);set("billingDocumentId",id);if(b){set("currency",b.currency||"USD");}}}><option value="">Select posted billing document</option>{billing.map(b=><option key={b.id} value={b.id}>{b.billingNumber||b.number||"Billing"} · {b.customerCode||"Customer"} · {b.currency||"USD"} {Number(b.totalAmount||b.total||0).toFixed(2)}</option>)}</select></div><div className="form-field"><label>Amount *</label><input className="form-input" type="number" min="0.01" step="0.01" value={form.amount} onChange={e=>set("amount",e.target.value)} /></div><div className="form-field"><label>Currency *</label><select className="form-input" value={form.currency} onChange={e=>set("currency",e.target.value)}><option>USD</option><option>ZWL</option></select></div><div className="form-field"><label>Reference</label><input className="form-input" value={form.reference} onChange={e=>set("reference",e.target.value)} placeholder="Bank / receipt reference" /></div></div></section></div>;
}
